### ISSUE TITLE
Error after updating ember-cli-htmlbars [Ember 2.11.0]

### ISSUE THREAD

**Issue by psteininger** [piceaTech/ember-rapid-forms#151]
This issue may be caused by updates in #149 and #150 (which are related to #148 )

I have a form that is backed by a model, which extends `Ember.Object` not `DS.Model`, and has `ember-cp-validations`. 
```javascript
...

const Validations = buildValidations({
  password: [
    validator('presence', {
      presence: true
    })
  ],
  passwordConfirmation: [
    validator('presence', {
      presence: true
    }),
    validator('confirmation', {
      on: 'password'
    })
  ],
  'strength.score': [
    validator('number', {
      gt: 1
    })
  ]
});

export default Ember.Object.extend(Validations, InputErrors, helper,{

  modelName: "password",
  password: "",
  passwordConfirmation: "",
  isSubmitting: false,
  isSubmitted: false,

  init() {
    this._super(...arguments);
    this.set('countdownTime', new Date());
  },

  strength: computed('password', function () {
    return strength(this.get('password'));
  }),
  preventSubmit: computed('isValid', 'isSubmitting', 'isSubmitted', function () {
    return !this.get('isValid') || this.get('isSubmitting') || this.get('isSubmitted');
  })
});
...
```
```javascript
//routes/password.js
...
model(){
    return Password.create(getOwner(this).ownerInjection(),{});
  },
...
```

Here's the HBS:
```handlebars
 {{#em-form model=model action="commitChange" submitButton=false}}
                            {{em-input property="password" label="Password" type="password"}}
                            {{em-input property="passwordConfirmation" label="Password (confirm)" type="password"}}
...
{{/em-form}}
```

Whether I have the validations turned on or off (code commented out completely) I get an the following error, when I change the value of any field. I also tried using a `DS.Model` and had the same results.

`Property set failed: object in path "mainComponent.model" could not be found or was destroyed.`

Stack trace:
```
"Error
    at setPath (http://localhost:4200/assets/vendor.js:33223:15)
    at Object.set (http://localhost:4200/assets/vendor.js:33143:14)
    at AliasedProperty_set [as set] (http://localhost:4200/assets/vendor.js:26861:36)
    at Object.set (http://localhost:4200/assets/vendor.js:33159:12)
    at RootPropertyReference.(anonymous function) [as __UPDATE__ [id=__ember1487078295307136334426758]] (http://localhost:4200/assets/vendor.js:26131:19)
    at Class._emberViews.CoreView.extend._CoreView$extend.(anonymous function) [as __PROPERTY_DID_CHANGE__ [id=__ember14870782953071323788122379]] (http://localhost:4200/assets/vendor.js:18489:55)
    at Object.propertyDidChange (http://localhost:4200/assets/vendor.js:32775:31)
    at Object.set (http://localhost:4200/assets/vendor.js:33176:34)
    at Class._elementValueDidChange (http://localhost:4200/assets/vendor.js:52092:19)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:28995:18)"
```

I am not sure how to diagnose it, and how to fix it. Perhaps @spruce could shed a light?

**Comment by psteininger** [comment]
@spruce it looks like the issue is that the `root` in the following method evaluates to `undefined`
```javascript
 function setPath(root, path, value, tolerant) {
    // get the last part of the path
    var keyName = path.slice(path.lastIndexOf('.') + 1);

    // get the first part of the part
    path = path === keyName ? keyName : path.slice(0, path.length - (keyName.length + 1));

    // unless the path is this, look up the first part to
    // get the root
    if (path !== 'this') {
      root = _emberMetalProperty_get._getPath(root, path);
    }

    if (!keyName || keyName.length === 0) {
      throw new _emberMetalError.default('Property set failed: You passed an empty path');
    }

    if (!root) {
      if (tolerant) {
        return;
      } else {
        throw new _emberMetalError.default('Property set failed: object in path "' + path + '" could not be found or was destroyed.');
      }
    }

    return set(root, keyName, value);
  }
```
the value of `root` before these lines 
```javascript
 if (path !== 'this') {
      root = _emberMetalProperty_get._getPath(root, path);
    }
```
has the input tag as the viewElement. So it appears that the model is not propagated down from the `{{em-form}}`` to the `{{em-input}}`. I'll try to do some more digging today.

**Comment by psteininger** [comment]
Another observation:
```
Ember.get(root, 'mainComponent.form')
> undefined
Ember.get(root, 'mainComponent.model')
> undefined
```

**Comment by psteininger** [comment]
I just noticed that this:
```javascript
Ember.get(root, 'mainComponent.parentView.model')
```
produces the actual model

**Comment by psteininger** [comment]
I am coming to a conclusion that a deprecation is at fault here:
```
Please use the new form.input helper defined in 1.0.0beta10
```

Perhaps I need to define the form and input differently

**Comment by psteininger** [comment]
Ok, so I have changed my hbs to:
```handlebars
 {{#em-form model=model action="commitChange" submitButton=false as |f|}}
                            {{f.input property="password" label="Password" type="password"}}
                            {{f.input property="passwordConfirmation" label="Password (confirm)" type="password"}}
...
{{/em-form}}
```
and the form works, but I hit other issues with the `ember-cp-validations` integration. I will fix that and do a PR soon. 

In the meantime, I think it would be worth documenting the change to the handlebars setup and/or make things work both ways (old way and new way).

**Comment by spruce** [comment]
Sorry for not checking in here lately (2 month, ups). Did you have a PR on the thing you mentioned. Now the docs are showing the new way to use the forms. Should there be anything else changed?

**Comment by spruce** [comment]
@psteininger anything new? elsewise I gonna close this as this project doesn't support 2.10 any longer.

**Comment by psteininger** [comment]
@spruce ok to close. It's been a long time since I solved the issue, and I just don't remember how.
